### ISSUE TITLE
Make requests made with the wrong HTTP method return 404

### ISSUE THREAD

**Issue by snaco** [dayal96/monkey-do#2]
example config.mnkc:
```
port: 8484
handlers:
  - id: create_item
    method: POST
    route: my/api/create
    response:
      status: 200
      body: Success!
```

on GET localhost:8484/my/api/create the response will be 200: Success! we should have it be 404 instead since a GET my/api/create is not defined
